const API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kiosk/card-login';
const USER_KEY='lunch-poc-current-user-v17',KIOSK_KEY='lunch-kiosk-session-v1',LANGUAGE_KEY='lunch-poc-language-v5';
let language=localStorage.getItem(LANGUAGE_KEY)||'sv',busy=false;
const copy={en:{title:'Lunch kiosk',intro:'Scan your card to order lunch.',card:'Card number',go:'Continue',checking:'Checking card...',external:'External account could not be opened.'},sv:{title:'Lunchkiosk',intro:'Skanna ditt kort för att beställa lunch.',card:'Kortnummer',go:'Fortsätt',checking:'Kontrollerar kort...',external:'Det externa kontot kunde inte öppnas.'},fi:{title:'Lounaskioski',intro:'Tilaa lounas skannaamalla korttisi.',card:'Kortin numero',go:'Jatka',checking:'Tarkistetaan korttia...',external:'Ulkoista tiliä ei voitu avata.'}};
const t=()=>copy[language]||copy.sv;
function normalize(value){const digits=String(value||'').replace(/\D/g,'');return digits.length>5?digits.slice(-5):digits;}
function apply(){document.documentElement.lang=language;languageSelect.value=language;title.textContent=t().title;intro.textContent=t().intro;cardLabel.textContent=t().card;loginButton.textContent=t().go;}
function show(text,type=''){message.textContent=text;message.className=`message ${type}`;}
function clearSessions(){localStorage.removeItem(USER_KEY);sessionStorage.removeItem(KIOSK_KEY);}
async function login(raw){if(busy)return;const cardNumber=normalize(raw);if(!cardNumber)return;busy=true;loginButton.disabled=true;show(t().checking,'loading');try{const response=await fetch(API,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({cardNumber})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.details||body.error||`HTTP ${response.status}`);const ownerType=String(body.ownerType||'').toLowerCase();if(!['employee','external'].includes(ownerType))throw new Error(t().external);let user;if(ownerType==='employee'){const employeeNumber=String(body.employeeNo??body.employeeNumber??'');if(!employeeNumber)throw new Error(t().external);const employeeName=body.displayName||body.employeeName||employeeNumber;user={ownerType:'employee',employeeNumber,employeeName,displayName:employeeName,firstName:body.firstName||'',lastName:body.lastName||'',email:body.email||null,cardNumber,active:true};}else{const externalAccountId=Number(body.externalAccountId);const cardId=Number(body.cardId);if(!externalAccountId||!cardId)throw new Error(t().external);const displayName=body.displayName||body.cardHolderName||`External ${externalAccountId}`;user={ownerType:'external',externalAccountId,cardId,displayName,employeeName:displayName,cardHolderName:body.cardHolderName||'',companyName:body.companyName||'',cardNumber,active:true};}localStorage.setItem(USER_KEY,JSON.stringify(user));sessionStorage.setItem(KIOSK_KEY,JSON.stringify({...body,...user,ownerType,cardNumber,loginTime:new Date().toISOString()}));location.replace('order.html');}catch(error){show(error.message,'error');cardInput.value='';cardInput.focus();}finally{busy=false;loginButton.disabled=false;}}
clearSessions();apply();cardForm.addEventListener('submit',event=>{event.preventDefault();login(cardInput.value);});languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);apply();cardInput.focus();});window.addEventListener('load',()=>cardInput.focus());
