const USER_KEY='lunch-poc-current-user-v17',KIOSK_KEY='lunch-kiosk-session-v1',LANGUAGE_KEY='lunch-poc-language-v5',TIMEOUT_SECONDS=60;
let session=null,seconds=TIMEOUT_SECONDS,interval;
try{session=JSON.parse(sessionStorage.getItem(KIOSK_KEY)||'null');}catch{}
if(!session||!['employee','external'].includes(session.ownerType)||!localStorage.getItem(USER_KEY))location.replace('index.html');
const language=localStorage.getItem(LANGUAGE_KEY)||'sv';
const copy={en:{logout:'Log out',employee:'Employee'},sv:{logout:'Logga ut',employee:'Anställd'},fi:{logout:'Kirjaudu ulos',employee:'Työntekijä'}}[language]||{logout:'Logga ut',employee:'Anställd'};
signedInName.textContent=session.employeeName||session.displayName||session.cardHolderName||'Lunchkiosk';signedInNumber.textContent=session.ownerType==='external'?(session.companyName||'External'):`${copy.employee} ${session.employeeNumber||session.employeeNo||''}`;logoutButton.textContent=copy.logout;
function update(){timeoutCounter.textContent=`${seconds} s`;timeoutCounter.classList.toggle('warning',seconds<=15&&seconds>5);timeoutCounter.classList.toggle('urgent',seconds<=5);}
function reset(){seconds=TIMEOUT_SECONDS;update();}
function logout(){clearInterval(interval);localStorage.removeItem(USER_KEY);sessionStorage.removeItem(KIOSK_KEY);location.replace('index.html');}
function wireFrame(){try{const win=orderingFrame.contentWindow,doc=orderingFrame.contentDocument;if(!doc)return;['pointerdown','keydown','touchstart','input','change','click'].forEach(name=>doc.addEventListener(name,reset,{passive:true}));const guestLinks=doc.querySelectorAll('a[href*="guest-order"]');guestLinks.forEach(link=>link.hidden=session.ownerType==='external');const originalLogout=doc.querySelector('#logoutButton');if(originalLogout)originalLogout.addEventListener('click',event=>{event.preventDefault();logout();},true);if(win.location.pathname.endsWith('/login.html'))logout();}catch(error){console.warn('Could not attach kiosk activity handlers',error);}}
window.addEventListener('message',event=>{if(event.origin===window.location.origin&&event.source===orderingFrame.contentWindow&&event.data?.type==='LUNCH_KIOSK_ORDER_SAVED')logout();});orderingFrame.addEventListener('load',wireFrame);logoutButton.addEventListener('click',logout);['pointerdown','keydown','touchstart'].forEach(name=>document.addEventListener(name,reset,{passive:true}));reset();interval=setInterval(()=>{seconds--;update();if(seconds<=0)logout();},1000);
