const CARD_LOGIN_API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kiosk/card-login';
const SESSION_KEY='cafe-kiosk-card-session-v1',LANGUAGE_KEY='lunch-poc-language-v5';
let language=localStorage.getItem(LANGUAGE_KEY)||'sv',busy=false;
const copy={en:{title:'Scan your card',help:'Hold the card against the reader to begin.',card:'Card number',go:'Continue',checking:'Checking card...'},sv:{title:'Skanna ditt kort',help:'Håll kortet mot läsaren för att börja.',card:'Kortnummer',go:'Fortsätt',checking:'Kontrollerar kort...'},fi:{title:'Skannaa korttisi',help:'Aloita pitämällä korttia lukijaa vasten.',card:'Kortin numero',go:'Jatka',checking:'Tarkistetaan korttia...'}};
const t=()=>copy[language]||copy.sv;
function normalizeCardNumber(value){const digits=String(value??'').replace(/\D/g,'');return digits.length>5?digits.slice(-5):digits;}
function applyText(){document.documentElement.lang=language;languageSelect.value=language;loginTitle.textContent=t().title;loginHelp.textContent=t().help;cardLabel.textContent=t().card;loginButton.textContent=t().go;}
function message(value,type=''){loginMessage.textContent=value;loginMessage.className=`login-message ${type}`;}
async function login(raw){if(busy)return;const cardNumber=normalizeCardNumber(raw);if(!cardNumber)return;busy=true;loginButton.disabled=true;message(t().checking,'loading');try{const response=await fetch(CARD_LOGIN_API,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({cardNumber})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||body.details||`HTTP ${response.status}`);sessionStorage.setItem(SESSION_KEY,JSON.stringify({...body,cardNumber,loginTime:new Date().toISOString()}));location.replace('order.html');}catch(error){message(error.message,'error');cardInput.value='';cardInput.focus();}finally{busy=false;loginButton.disabled=false;}}
sessionStorage.removeItem(SESSION_KEY);applyText();cardForm.addEventListener('submit',event=>{event.preventDefault();login(cardInput.value);});languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);applyText();cardInput.focus();});window.addEventListener('load',()=>cardInput.focus());
