const API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kiosk';
const PRODUCT_API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kiosk/products';
const SESSION_KEY='cafe-kiosk-card-session-v1',LANGUAGE_KEY='lunch-poc-language-v5',SESSION_SECONDS=60;
let language=localStorage.getItem(LANGUAGE_KEY)||'sv',session=null,layout=null,seconds=SESSION_SECONDS,timer,purchasing=false,toastTimer;
const products=new Map(),quantities=new Map();
const copy={en:{cancel:'Cancel',choose:'Choose products',help:'Use plus and minus, then complete the purchase.',none:'No products selected',selected:n=>`${n} product${n===1?'':'s'} selected`,select:'Select a product to continue',total:'Total',buy:'Buy',clear:'Clear',loading:'Loading products...',empty:'No products are available.',employee:n=>`Employee ${n}`,prepaid:b=>`Prepaid · Balance ${b}`,postpaid:'Postpaid',invoice:'Invoice',availableCredit:b=>`Available credit ${b}`,success:'Purchase completed',failed:'Purchase failed',balance:'Insufficient balance.',credit:'Credit limit exceeded.'},sv:{cancel:'Avbryt',choose:'Välj produkter',help:'Använd plus och minus och slutför sedan köpet.',none:'Inga produkter valda',selected:n=>`${n} produkt${n===1?'':'er'} vald${n===1?'':'a'}`,select:'Välj en produkt för att fortsätta',total:'Totalt',buy:'Köp',clear:'Töm',loading:'Laddar produkter...',empty:'Inga produkter är tillgängliga.',employee:n=>`Anställd ${n}`,prepaid:b=>`Förbetalt · Saldo ${b}`,postpaid:'Efterbetalt',invoice:'Faktura',availableCredit:b=>`Tillgänglig kredit ${b}`,success:'Köpet genomfördes',failed:'Köpet misslyckades',balance:'Otillräckligt saldo.',credit:'Kreditgränsen har överskridits.'},fi:{cancel:'Peruuta',choose:'Valitse tuotteet',help:'Käytä plus- ja miinuspainikkeita ja suorita sitten osto.',none:'Ei valittuja tuotteita',selected:n=>`${n} tuotetta valittu`,select:'Jatka valitsemalla tuote',total:'Yhteensä',buy:'Osta',clear:'Tyhjennä',loading:'Ladataan tuotteita...',empty:'Tuotteita ei ole saatavilla.',employee:n=>`Työntekijä ${n}`,prepaid:b=>`Ennakkomaksu · Saldo ${b}`,postpaid:'Jälkimaksu',invoice:'Lasku',availableCredit:b=>`Käytettävissä oleva luotto ${b}`,success:'Osto onnistui',failed:'Osto epäonnistui',balance:'Saldo ei riitä.',credit:'Luottoraja on ylitetty.'}};
const t=()=>copy[language]||copy.sv;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function name(p){return (language==='fi'?p.nameFi:language==='en'?p.nameEn:p.nameSv)||p.nameSv||p.nameEn||p.nameFi||`#${p.productId}`;}
function money(cents){const locale=language==='fi'?'fi-FI':language==='sv'?'sv-FI':'en-FI';return new Intl.NumberFormat(locale,{style:'currency',currency:'EUR'}).format(Number(cents||0)/100);}
function count(){return[...quantities.values()].reduce((a,b)=>a+b,0);}function total(){let n=0;for(const[id,q]of quantities)n+=Math.round(Number(products.get(id).price)*100)*q;return n;}
function details(){if(session.ownerType==='employee')return t().employee(session.employeeNo);if(session.accountMode==='Prepaid')return [t().prepaid(money(Number(session.availableBalanceCents||0))),session.companyName].filter(Boolean).join(' · ');const mode=session.accountMode==='Invoice'?t().invoice:t().postpaid;const available=Number.isFinite(Number(session.availableCreditCents))?Number(session.availableCreditCents):Math.max(Number(session.creditLimitCents||0)-Number(session.outstandingCents||0),0);return [mode,session.companyName,t().availableCredit(money(available))].filter(Boolean).join(' · ');}
function visual(p){return p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${esc(p.icon||'📦')}</span>`:`<span>${esc(p.icon||'📦')}</span>`;}
function card(p){const q=quantities.get(p.productId)||0;return`<article class="product ${q?'selected':''}" data-id="${p.productId}"><div class="image">${visual(p)}</div><div class="info"><strong>${esc(name(p))}</strong><span>${money(Math.round(Number(p.price)*100))}</span></div><div class="stepper"><button class="minus" ${q?'':'disabled'}>−</button><output>${q}</output><button class="plus">+</button></div></article>`;}
function render(){if(!layout)return;products.clear();const cols={1:[],2:[]};layout.items.filter(x=>x.isVisible&&x.product.active).sort((a,b)=>a.columnNo-b.columnNo||a.rowNo-b.rowNo).forEach(x=>{products.set(x.productId,x.product);cols[x.columnNo].push(x.product);});column1.innerHTML=cols[1].map(card).join('');column2.innerHTML=cols[2].map(card).join('');emptyState.hidden=cols[1].length+cols[2].length>0;emptyState.textContent=t().empty;cartTotal.textContent=money(total());selectionSummary.textContent=count()?t().selected(count()):t().none;statusText.textContent=count()?`${t().total} ${money(total())}`:t().select;buyButton.disabled=!count()||purchasing;clearButton.disabled=!count()||purchasing;}
function applyText(){document.documentElement.lang=language;languageSelect.value=language;cancelButton.textContent=t().cancel;chooseTitle.textContent=t().choose;chooseHelp.textContent=t().help;buyButton.textContent=t().buy;clearButton.textContent=t().clear;customerDetails.textContent=details();render();}
async function json(url,options={}){const r=await fetch(url,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||b.details||`HTTP ${r.status}`);return b;}
function showStatus(message,type=''){status.textContent=message;status.className=message?`status show ${type}`:'status';}
function toastMessage(message,type,duration){toast.textContent=message;toast.className=`toast show ${type}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.className='toast',duration);}
function localError(message){const x=String(message||'').toLowerCase();if(x.includes('insufficient prepaid balance'))return t().balance;if(x.includes('credit limit exceeded'))return t().credit;return message||t().failed;}
function reset(){seconds=SESSION_SECONDS;update();}function update(){timeoutCounter.textContent=`${seconds} s`;timeoutCounter.classList.toggle('warning',seconds<=15&&seconds>5);timeoutCounter.classList.toggle('urgent',seconds<=5);}function leave(){sessionStorage.removeItem(SESSION_KEY);clearInterval(timer);location.replace('index.html');}
async function load(){showStatus(t().loading,'loading');try{const [loadedLayout,latestProducts]=await Promise.all([json(`${API}/layouts/default`),json(PRODUCT_API)]);const productById=new Map(latestProducts.map(product=>[Number(product.productId),product]));loadedLayout.items=loadedLayout.items.map(item=>{const latest=productById.get(Number(item.productId));return latest?{...item,product:{...item.product,...latest}}:item;});layout=loadedLayout;showStatus('');render();}catch(e){showStatus(e.message,'error');}}
async function buy(){if(purchasing||!count())return;purchasing=true;render();showStatus('');const requestId=crypto.randomUUID(),items=[...quantities].map(([productId,quantity])=>({productId,quantity}));try{const sale=await json(`${API}/sales`,{method:'POST',body:JSON.stringify({requestId,cardNumber:session.cardNumber,createdBy:'Kiosk',items})});toastMessage(`${t().success}: ${money(sale.totalCents)}`,'success',1200);sessionStorage.removeItem(SESSION_KEY);clearInterval(timer);setTimeout(()=>location.replace('index.html'),1200);}catch(e){purchasing=false;const message=localError(e.message);showStatus(`${t().failed}: ${message}`,'error');toastMessage(`${t().failed}: ${message}`,'error',6000);render();reset();}}
function step(e){reset();const b=e.target.closest('.stepper button');if(!b)return;const id=Number(b.closest('[data-id]').dataset.id),q=Math.max(0,(quantities.get(id)||0)+(b.classList.contains('plus')?1:-1));q?quantities.set(id,q):quantities.delete(id);render();}
try{session=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch{session=null;}if(!session||!session.cardNumber)location.replace('index.html');else{customerName.textContent=session.displayName||'Café Kiosk';applyText();load();reset();timer=setInterval(()=>{seconds--;update();if(seconds<=0)leave();},1000);}
column1.addEventListener('click',step);column2.addEventListener('click',step);languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);applyText();reset();});cancelButton.addEventListener('click',leave);clearButton.addEventListener('click',()=>{quantities.clear();render();reset();});buyButton.addEventListener('click',buy);['pointerdown','keydown','touchstart'].forEach(x=>document.addEventListener(x,reset,{passive:true}));
