const API_ROOT='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kiosk';
const LAYOUT_API=`${API_ROOT}/layouts/default`;
const SALES_API=`${API_ROOT}/sales`;
const SESSION_KEY='cafe-kiosk-card-session-v1';
const LANGUAGE_KEY='lunch-poc-language-v5';
const SESSION_SECONDS=60;
let language=localStorage.getItem(LANGUAGE_KEY)||'sv';
let session;let layout;let products=new Map();let quantities=new Map();let seconds=SESSION_SECONDS;let timer;let purchasing=false;
const copy={
 en:{cancel:'Cancel',choose:'Choose products',help:'Use plus and minus, then complete the purchase.',none:'No products selected',selected:n=>`${n} product${n===1?'':'s'} selected`,select:'Select a product to continue',total:'Total',buy:'Buy',clear:'Clear',loading:'Loading products...',empty:'No products are available.',employee:n=>`Employee ${n}`,prepaid:b=>`Prepaid · Balance ${b}`,postpaid:'Postpaid',invoice:'Invoice',success:'Purchase completed',failed:'Purchase failed'},
 sv:{cancel:'Avbryt',choose:'Välj produkter',help:'Använd plus och minus och slutför sedan köpet.',none:'Inga produkter valda',selected:n=>`${n} produkt${n===1?'':'er'} vald${n===1?'':'a'}`,select:'Välj en produkt för att fortsätta',total:'Totalt',buy:'Köp',clear:'Töm',loading:'Laddar produkter...',empty:'Inga produkter är tillgängliga.',employee:n=>`Anställd ${n}`,prepaid:b=>`Förbetalt · Saldo ${b}`,postpaid:'Efterbetalt',invoice:'Faktura',success:'Köpet genomfördes',failed:'Köpet misslyckades'},
 fi:{cancel:'Peruuta',choose:'Valitse tuotteet',help:'Käytä plus- ja miinuspainikkeita ja suorita sitten osto.',none:'Ei valittuja tuotteita',selected:n=>`${n} tuotetta valittu`,select:'Jatka valitsemalla tuote',total:'Yhteensä',buy:'Osta',clear:'Tyhjennä',loading:'Ladataan tuotteita...',empty:'Tuotteita ei ole saatavilla.',employee:n=>`Työntekijä ${n}`,prepaid:b=>`Ennakkomaksu · Saldo ${b}`,postpaid:'Jälkimaksu',invoice:'Lasku',success:'Osto onnistui',failed:'Osto epäonnistui'}
};
const t=()=>copy[language]||copy.sv;
function escapeHtml(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function name(p){const preferred=language==='fi'?p.nameFi:language==='en'?p.nameEn:p.nameSv;return preferred||p.nameSv||p.nameEn||p.nameFi||`#${p.productId}`;}
function moneyCents(c){const locale=language==='fi'?'fi-FI':language==='sv'?'sv-FI':'en-FI';return new Intl.NumberFormat(locale,{style:'currency',currency:'EUR'}).format(Number(c||0)/100);}
function moneyPrice(p){return moneyCents(Math.round(Number(p||0)*100));}
function count(){return [...quantities.values()].reduce((a,b)=>a+b,0);}
function total(){let sum=0;for(const [id,q] of quantities)sum+=Math.round(Number(products.get(id).price)*100)*q;return sum;}
function details(){if(session.ownerType==='employee')return t().employee(session.employeeNo);if(session.accountMode==='Prepaid')return t().prepaid(moneyCents(session.availableBalanceCents));return session.companyName?[session.accountMode==='Invoice'?t().invoice:t().postpaid,session.companyName].join(' · '):(session.accountMode==='Invoice'?t().invoice:t().postpaid);}
function applyText(){document.documentElement.lang=language;languageSelect.value=language;cancelButton.textContent=t().cancel;chooseTitle.textContent=t().choose;chooseHelp.textContent=t().help;buyButton.textContent=t().buy;clearButton.textContent=t().clear;customerDetails.textContent=details();render();}
function productVisual(p){return p.imageUrl?`<img src="${escapeHtml(p.imageUrl)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${escapeHtml(p.icon||'📦')}</span>`:`<span>${escapeHtml(p.icon||'📦')}</span>`;}
function card(p){const q=quantities.get(p.productId)||0;return `<article class="product-card ${q?'selected':''}" data-id="${p.productId}"><div class="product-image">${productVisual(p)}</div><div class="product-info"><strong>${escapeHtml(name(p))}</strong><span>${moneyPrice(p.price)}</span></div><div class="stepper"><button class="minus" type="button" aria-label="Minus" ${q?'':'disabled'}>−</button><output>${q}</output><button class="plus" type="button" aria-label="Plus">+</button></div></article>`;}
function render(){if(!layout)return;const byColumn={1:[],2:[]};layout.items.filter(i=>i.isVisible&&i.product.active).sort((a,b)=>a.columnNo-b.columnNo||a.rowNo-b.rowNo).forEach(i=>{products.set(i.productId,i.product);byColumn[i.columnNo].push(i.product);});productColumn1.innerHTML=byColumn[1].map(card).join('');productColumn2.innerHTML=byColumn[2].map(card).join('');const has=byColumn[1].length+byColumn[2].length>0;emptyState.hidden=has;emptyState.textContent=t().empty;const n=count(),sum=total();cartTotal.textContent=moneyCents(sum);selectionSummary.textContent=n?t().selected(n):t().none;statusText.textContent=n?`${t().total} ${moneyCents(sum)}`:t().select;buyButton.disabled=!n||purchasing;clearButton.disabled=!n||purchasing;}
async function load(){showStatus(t().loading,'loading');try{layout=await fetchJson(LAYOUT_API);showStatus('','');render();}catch(e){showStatus(e.message,'error');}}
async function fetchJson(url,options={}){const r=await fetch(url,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.details||b.error||`HTTP ${r.status}`);return b;}
function showStatus(msg,type){status.textContent=msg;status.className=msg?`kiosk-status ${type}`:'kiosk-status';}
function reset(){seconds=SESSION_SECONDS;updateCounter();}
function updateCounter(){timeoutCounter.textContent=`${seconds} s`;timeoutCounter.classList.toggle('warning',seconds<=15&&seconds>5);timeoutCounter.classList.toggle('urgent',seconds<=5);}
function leave(){sessionStorage.removeItem(SESSION_KEY);clearInterval(timer);location.replace('index.html');}
function clearBasket(){quantities.clear();reset();render();}
async function buy(){if(purchasing||!count())return;purchasing=true;render();showStatus('', '');const requestId=crypto.randomUUID();const items=[...quantities].map(([productId,quantity])=>({productId,quantity}));try{const sale=await fetchJson(SALES_API,{method:'POST',body:JSON.stringify({requestId,cardNumber:session.cardNumber,createdBy:'Kiosk',items})});toast.textContent=`${t().success}: ${moneyCents(sale.totalCents)}`;toast.classList.add('show');sessionStorage.removeItem(SESSION_KEY);clearInterval(timer);setTimeout(()=>location.replace('index.html'),1200);}catch(e){purchasing=false;showStatus(`${t().failed}: ${e.message}`,'error');render();reset();}}
try{session=JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null');}catch{session=null;}if(!session||!session.cardNumber)location.replace('index.html');else{customerName.textContent=session.displayName||'Café Kiosk';customerDetails.textContent=details();applyText();load();reset();timer=setInterval(()=>{seconds-=1;updateCounter();if(seconds<=0)leave();},1000);}
productColumn1.addEventListener('click',step);productColumn2.addEventListener('click',step);function step(e){reset();const b=e.target.closest('.stepper button');if(!b)return;const id=Number(b.closest('[data-id]').dataset.id);const next=Math.max(0,(quantities.get(id)||0)+(b.classList.contains('plus')?1:-1));if(next)quantities.set(id,next);else quantities.delete(id);render();}
languageSelect.addEventListener('change',()=>{reset();language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);applyText();});cancelButton.addEventListener('click',leave);clearButton.addEventListener('click',clearBasket);buyButton.addEventListener('click',buy);['pointerdown','keydown','touchstart'].forEach(eventName=>document.addEventListener(eventName,reset,{passive:true}));
