const API_BASE='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api';
let orders=[],expanded=new Set(),loading=false,cancelling=false,currentCancellation=null,toastTimer;
const $=s=>document.querySelector(s),daySelect=$('#daySelect'),search=$('#employeeSearch'),mealSummary=$('#mealSummary'),dataNote=$('#dataNote'),refreshButton=$('#refreshButton'),cancelDialog=$('#cancelDialog'),cancelForm=$('#cancelForm');
const lang=()=>window.AdminI18n?.lang?.()||'en',locale=()=>({sv:'sv-SE',fi:'fi-FI',en:'en-GB'}[lang()]||'en-GB');
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const displayDate=v=>new Intl.DateTimeFormat(locale(),{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${v}T12:00:00`));
const portions=r=>r.reduce((n,o)=>n+Number(o.quantity||0),0);
const mealName=o=>lang()==='sv'?(o.nameSV||o.nameEN||o.nameFI):lang()==='fi'?(o.nameFI||o.nameEN||o.nameSV):(o.nameEN||o.nameSV||o.nameFI);
const text=()=>({en:{today:'Today',refresh:'Refresh',employee:'Employee',guest:'Guest',noTask:'No work task or project',cancel:'Cancel',cancelLunch:'Cancel lunch',dish:'Dish',date:'Date',task:'Work task / project',quantity:'Quantity to cancel',active:q=>`Active quantity: ${q}`,reason:'Reason',info:'Additional information',by:'Cancelled by',back:'Back',submit:'Cancel lunch',saving:'Cancelling...',requiredOther:'Additional information is required when reason is Other.',success:n=>`${n} lunch${n===1?'':'es'} cancelled.`},sv:{today:'I dag',refresh:'Uppdatera',employee:'Personal',guest:'Gäst',noTask:'Ingen arbetsuppgift eller projekt',cancel:'Avboka',cancelLunch:'Avboka lunch',dish:'Maträtt',date:'Datum',task:'Arbetsuppgift / projekt',quantity:'Antal att avboka',active:q=>`Aktivt antal: ${q}`,reason:'Orsak',info:'Ytterligare information',by:'Avbokad av',back:'Tillbaka',submit:'Avboka lunch',saving:'Avbokar...',requiredOther:'Ytterligare information krävs när orsaken är Annat.',success:n=>`${n} lunch${n===1?'':'er'} avbokad${n===1?'':'e'}.`},fi:{today:'Tänään',refresh:'Päivitä',employee:'Henkilöstö',guest:'Vieras',noTask:'Ei työtehtävää tai projektia',cancel:'Peruuta',cancelLunch:'Peruuta lounas',dish:'Ruoka',date:'Päivä',task:'Työtehtävä / projekti',quantity:'Peruttava määrä',active:q=>`Aktiivinen määrä: ${q}`,reason:'Syy',info:'Lisätiedot',by:'Peruuttaja',back:'Takaisin',submit:'Peruuta lounas',saving:'Peruutetaan...',requiredOther:'Lisätiedot vaaditaan, kun syy on Muu.',success:n=>`${n} lounasta peruutettu.`}}[lang()]||{});
const cancellationReasons=()=>({
    en:{INSUFFICIENT_PORTIONS:'Insufficient portions',EMPLOYEE_REQUEST:'Employee requested removal',EMPLOYEE_ABSENT:'Employee absent',WRONG_DISH:'Wrong dish',KITCHEN_CORRECTION:'Kitchen correction',OTHER:'Other'},
    sv:{INSUFFICIENT_PORTIONS:'För få portioner',EMPLOYEE_REQUEST:'Personen begärde avbokning',EMPLOYEE_ABSENT:'Personen frånvarande',WRONG_DISH:'Fel maträtt',KITCHEN_CORRECTION:'Kökets korrigering',OTHER:'Övrigt'},
    fi:{INSUFFICIENT_PORTIONS:'Liian vähän annoksia',EMPLOYEE_REQUEST:'Henkilö pyysi peruutusta',EMPLOYEE_ABSENT:'Henkilö poissa',WRONG_DISH:'Väärä ruoka',KITCHEN_CORRECTION:'Keittiön korjaus',OTHER:'Muu'}
}[lang()]||{});
function renderCancellationReasons(selectedValue){
    const select=$('#cancelReason'),selected=selectedValue||select.value||'INSUFFICIENT_PORTIONS',reasons=cancellationReasons();
    select.innerHTML=Object.entries(reasons).map(([value,label])=>`<option value="${value}">${esc(label)}</option>`).join('');
    select.value=reasons[selected]?selected:'INSUFFICIENT_PORTIONS';
    $('#cancelReasonText').required=select.value==='OTHER';
}
const category=v=>({en:{main:'Main dish',vegetarian:'Vegetarian',soup:'Soup',salad:'Salad',dessert:'Dessert'},sv:{main:'Huvudrätt',vegetarian:'Vegetarisk',soup:'Soppa',salad:'Sallad',dessert:'Efterrätt'},fi:{main:'Pääruoka',vegetarian:'Kasvisruoka',soup:'Keitto',salad:'Salaatti',dessert:'Jälkiruoka'}}[lang()]?.[String(v||'').toLowerCase()]||v||'');
async function api(path,options={}){const r=await fetch(`${API_BASE}${path}`,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}}),type=r.headers.get('content-type')||'',b=type.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(b?.details||b?.error||b||`HTTP ${r.status}`);return b;}
function filtered(){const q=search.value.trim().toLowerCase();return q?orders.filter(o=>o.employeeName.toLowerCase().includes(q)||String(o.employeeNo).includes(q)||String(o.workTask||'').toLowerCase().includes(q)):orders;}
function groups(rows){const m=new Map();for(const o of rows){const k=`${o.itemType||'meal'}:${o.mealId}`;if(!m.has(k))m.set(k,{key:k,name:mealName(o),category:category(o.category),itemType:o.itemType||'meal',rows:[]});m.get(k).rows.push(o)}return[...m.values()].sort((a,b)=>portions(b.rows)-portions(a.rows)||a.name.localeCompare(b.name));}
function orderRow(o,t){const id=o.orderType==='guest'?o.guestOrderId:o.orderId;return `<div class="person-order"><span><strong>${esc(o.employeeName)}</strong><small>${o.orderType==='guest'?esc(o.workTask||t.noTask):esc(o.employeeNo)}</small></span><div class="person-order-actions"><strong>${o.quantity}</strong>${o.canCancel?`<button type="button" class="cancel-order-button" data-order-type="${o.orderType}" data-order-id="${id}">${esc(t.cancel)}</button>`:''}</div></div>`;}
function card(g){const open=expanded.has(g.key),t=text(),employees=g.rows.filter(o=>o.orderType==='employee').sort((a,b)=>a.employeeName.localeCompare(b.employeeName)),guests=g.rows.filter(o=>o.orderType==='guest').sort((a,b)=>a.employeeName.localeCompare(b.employeeName)),subtitle=[g.category,employees.length?`${portions(employees)} ${t.employee.toLowerCase()}`:'',guests.length?`${portions(guests)} ${t.guest.toLowerCase()}`:''].filter(Boolean).join(' · ');return `<article class="expandable-meal ${open?'open':''}" data-key="${g.key}"><button class="meal-expand-button" type="button"><span class="meal-expand-chevron"></span><span class="summary-meal"><strong>${esc(g.name)}</strong><span>${esc(subtitle)}</span></span><span class="portion-count">${portions(g.rows)}</span></button><div class="meal-people">${employees.length?`<section class="people-section"><h3>${esc(t.employee)}</h3>${employees.map(o=>orderRow(o,t)).join('')}</section>`:''}${guests.length?`<section class="people-section guest"><h3>${esc(t.guest)}</h3>${guests.map(o=>orderRow(o,t)).join('')}</section>`:''}</div></article>`;}
function render(){const rows=filtered(),employees=rows.filter(o=>o.orderType==='employee'),guests=rows.filter(o=>o.orderType==='guest'),g=groups(rows);$('#selectedDayHeading').textContent=displayDate(daySelect.value);$('#totalLunches').textContent=portions(rows);$('#employeeLunches').textContent=portions(employees);$('#guestLunches').textContent=portions(guests);$('#mealTypes').textContent=g.length;mealSummary.innerHTML=g.map(card).join('');$('#emptyState').hidden=g.length>0;}
async function load(preserveExpanded=false){if(loading||!daySelect.value)return;loading=true;refreshButton.disabled=true;try{const previous=preserveExpanded?new Set(expanded):new Set(),d=encodeURIComponent(daySelect.value),p=await api(`/kitchen/orders?dateFrom=${d}&dateTo=${d}`);orders=p.orders||[];expanded=previous;render();dataNote.textContent=`${p.summary?.orderRows??orders.length} order rows loaded from Azure.`;}catch(e){console.error(e);orders=[];render();dataNote.textContent=`Load failed: ${e.message}`;showToast(dataNote.textContent);}finally{loading=false;refreshButton.disabled=false;}}
function findOrder(type,id){return orders.find(o=>o.orderType===type&&Number(type==='guest'?o.guestOrderId:o.orderId)===Number(id));}
function openCancellation(order){currentCancellation=order;const t=text();$('#cancelTitle').textContent=t.cancelLunch;$('#cancelPersonLabel').textContent=order.orderType==='guest'?t.guest:t.employee;$('#cancelPerson').textContent=`${order.employeeName} · ${order.employeeNo}`;$('#cancelMealLabel').textContent=t.dish;$('#cancelMeal').textContent=mealName(order);$('#cancelDateLabel').textContent=t.date;$('#cancelDate').textContent=displayDate(order.menuDate);$('#cancelTaskLabel').textContent=t.task;$('#cancelTask').textContent=order.workTask||t.noTask;$('#cancelTaskRow').hidden=order.orderType!=='guest';$('#cancelQuantityLabel').textContent=t.quantity;$('#cancelQuantity').innerHTML=Array.from({length:order.activeQuantity},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');$('#cancelAvailable').textContent=t.active(order.activeQuantity);$('#cancelReasonLabel').textContent=t.reason;$('#cancelReasonTextLabel').textContent=t.info;$('#cancelByLabel').textContent=t.by;$('#cancelBack').textContent=t.back;$('#confirmCancellation').textContent=t.submit;renderCancellationReasons('INSUFFICIENT_PORTIONS');$('#cancelReasonText').value='';$('#cancelError').hidden=true;cancelDialog.showModal();}
async function submitCancellation(e){e.preventDefault();if(cancelling||!currentCancellation)return;const t=text(),reasonCode=$('#cancelReason').value,reasonText=$('#cancelReasonText').value.trim();if(reasonCode==='OTHER'&&!reasonText){$('#cancelError').textContent=t.requiredOther;$('#cancelError').hidden=false;return;}cancelling=true;$('#confirmCancellation').disabled=true;$('#confirmCancellation').textContent=t.saving;try{const quantity=Number($('#cancelQuantity').value),payload={orderType:currentCancellation.orderType,quantity,reasonCode,reasonText:reasonText||null,cancelledBy:$('#cancelledBy').value.trim()};if(currentCancellation.orderType==='guest')payload.guestOrderId=currentCancellation.guestOrderId;else payload.orderId=currentCancellation.orderId;await api('/kitchen/order-cancellations',{method:'POST',body:JSON.stringify(payload)});cancelDialog.close();showToast(t.success(quantity));await load(true);}catch(error){console.error(error);$('#cancelError').textContent=error.message;$('#cancelError').hidden=false;}finally{cancelling=false;$('#confirmCancellation').disabled=false;$('#confirmCancellation').textContent=t.submit;}}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3000);}
function applyLanguage(){const t=text();$('#todayButton').textContent=t.today;refreshButton.textContent=t.refresh;renderCancellationReasons();if(cancelDialog.open&&currentCancellation)openCancellation(currentCancellation);}
function init(){applyLanguage();daySelect.value=dateKey(new Date());daySelect.addEventListener('change',()=>load());search.addEventListener('input',render);refreshButton.addEventListener('click',()=>load());$('#todayButton').addEventListener('click',()=>{daySelect.value=dateKey(new Date());load()});$('#printButton').addEventListener('click',()=>print());mealSummary.addEventListener('click',e=>{const cancel=e.target.closest('.cancel-order-button');if(cancel){e.stopPropagation();const order=findOrder(cancel.dataset.orderType,cancel.dataset.orderId);if(order)openCancellation(order);return;}const card=e.target.closest('[data-key]');if(!card)return;expanded.has(card.dataset.key)?expanded.delete(card.dataset.key):expanded.add(card.dataset.key);render();});$('#closeCancelDialog').addEventListener('click',()=>cancelDialog.close());$('#cancelBack').addEventListener('click',()=>cancelDialog.close());cancelForm.addEventListener('submit',submitCancellation);$('#cancelReason').addEventListener('change',()=>{$('#cancelReasonText').required=$('#cancelReason').value==='OTHER';});document.addEventListener('admin-language-changed',()=>{applyLanguage();render()});load();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
