const API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/kitchen/weekly-summary';
const $=s=>document.querySelector(s),picker=$('#weekPicker'),status=$('#statisticsStatus');
const lang=()=>window.AdminI18n?.lang?.()||'en',locale=()=>lang()==='sv'?'sv-FI':lang()==='fi'?'fi-FI':'en-GB';
const copy={en:{main:'Main dishes',salads:'Salads',total:'Total',cancelled:'Cancelled meals',none:'No data',note:'Salad quantities are ordered portions. Salad cancellations are not implemented yet.'},sv:{main:'Huvudrätter',salads:'Sallader',total:'Totalt',cancelled:'Avbokade maträtter',none:'Inga data',note:'Salladsmängderna är beställda portioner. Avbokning av sallader är ännu inte implementerad.'},fi:{main:'Pääruoat',salads:'Salaatit',total:'Yhteensä',cancelled:'Peruutetut ruoat',none:'Ei tietoja',note:'Salaattimäärät ovat tilattuja annoksia. Salaattien peruutusta ei ole vielä toteutettu.'}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function currentWeek(){const d=new Date(),day=d.getDay()||7;d.setDate(d.getDate()+4-day);const y=d.getFullYear(),start=new Date(y,0,1),w=Math.ceil((((d-start)/86400000)+1)/7);return `${y}-W${String(w).padStart(2,'0')}`;}
function date(v,o={weekday:'short',day:'2-digit',month:'2-digit'}){return new Date(v+'T12:00:00').toLocaleDateString(locale(),o)}
function saladName(x){return lang()==='sv'?(x.nameSv||x.nameEn||x.nameFi):lang()==='fi'?(x.nameFi||x.nameSv||x.nameEn):(x.nameEn||x.nameSv||x.nameFi)}
function bars(el,items,label){const max=Math.max(...items.map(x=>x.value),1);el.innerHTML=items.length?items.map(x=>`<div class="reason-row"><strong>${esc(x.name)}</strong><i><b style="width:${x.value/max*100}%"></b></i><em>${x.value}</em></div>`).join(''):`<div class="empty-state"><strong>${copy[lang()].none}</strong></div>`;}
function chart(days){const c=copy[lang()],max=Math.max(...days.map(x=>x.total),1);$('#portionChart').innerHTML=`<div class="stacked-bars">${days.map(x=>`<div class="stacked-day"><div class="stacked-values"><span class="meal-bar" style="height:${x.meals/max*180}px" title="${c.main}: ${x.meals}"></span><span class="salad-bar" style="height:${x.salads/max*180}px" title="${c.salads}: ${x.salads}"></span></div><strong>${esc(date(x.date,{weekday:'short'}))}</strong><small>${x.total}</small></div>`).join('')}</div><div class="chart-legend"><span><i class="meal-key"></i>${c.main}</span><span><i class="salad-key"></i>${c.salads}</span></div>`;}
async function load(){status.className='statistics-status is-visible is-loading';status.textContent='Loading...';try{const r=await fetch(`${API}?week=${encodeURIComponent(picker.value)}`),d=await r.json();if(!r.ok)throw new Error(d.details||d.error);mealTotal.textContent=d.totals.meals;saladTotal.textContent=d.totals.salads;portionTotal.textContent=d.totals.total;cancelledTotal.textContent=d.totals.cancelled;cancelledPercent.textContent=`${d.totals.cancellationPercent}%`;const days=d.daily.filter(x=>x.isoDay<=5);dailyBreakdown.innerHTML=days.map(x=>`<tr><td><strong>${esc(date(x.date,{weekday:'long',day:'2-digit',month:'2-digit'}))}</strong></td><td>${x.meals}</td><td>${x.salads}</td><td>${x.total}</td><td>${x.cancelled}</td></tr>`).join('');chart(days);bars($('#saladPopularity'),d.saladPopularity.map(x=>({name:saladName(x),value:x.quantity})));bars($('#cancellationReasons'),d.cancellationReasons.map(x=>({name:String(x.reasonCode||'Other').replaceAll('_',' '),value:x.quantity})));statisticsNote.textContent=copy[lang()].note;status.className='statistics-status';status.textContent='';}catch(e){status.className='statistics-status is-visible is-error';status.textContent=e.message;}}
picker.value=currentWeek();picker.addEventListener('change',load);printStatistics.addEventListener('click',()=>print());document.addEventListener('admin-language-changed',load);load();