const API='https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api/images';
const $=s=>document.querySelector(s);let images=[],selected=null,pendingDelete=null,toastTimer;let language=localStorage.getItem('lunch-poc-language-v5')||'en';
const tr={en:{title:'Image library',sub:'Shared Cafe Kiosk product images',refresh:'Refresh',hero:'Review shared product images, usage and unused files.',all:'Images',used:'Used',unused:'Unused',search:'Search',ph:'Search by name or filename',only:'Show unused only',loading:'Loading images...',empty:'No images match the current filter.',preview:'Image preview',file:'File',type:'Type',size:'Size',uploaded:'Uploaded',creator:'Created by',usage:'Usage',close:'Close',del:'Delete unused image',delTitle:'Delete image?',delText:'This permanently removes the image from the library and Blob Storage. This cannot be undone.',cancel:'Cancel',confirm:'Delete permanently',deleting:'Deleting image...',deleted:'Image deleted',none:'Not used by any product',one:'Used by 1 product',many:n=>`Used by ${n} products`,unknown:'Unknown'},sv:{title:'Bildbibliotek',sub:'Gemensamma produktbilder for Cafe Kiosk',refresh:'Uppdatera',hero:'Granska gemensamma produktbilder, anvandning och oanvanda filer.',all:'Bilder',used:'Anvanda',unused:'Oanvanda',search:'Sok',ph:'Sok pa namn eller filnamn',only:'Visa endast oanvanda',loading:'Laddar bilder...',empty:'Inga bilder matchar filtret.',preview:'Forhandsvisning',file:'Fil',type:'Typ',size:'Storlek',uploaded:'Uppladdad',creator:'Skapad av',usage:'Anvandning',close:'Stang',del:'Ta bort oanvand bild',delTitle:'Ta bort bilden?',delText:'Bilden tas permanent bort fran biblioteket och Blob Storage. Atgarden kan inte angras.',cancel:'Avbryt',confirm:'Ta bort permanent',deleting:'Tar bort bilden...',deleted:'Bilden togs bort',none:'Anvands inte av nagon produkt',one:'Anvands av 1 produkt',many:n=>`Anvands av ${n} produkter`,unknown:'Okand'},fi:{title:'Kuvakirjasto',sub:'Cafe Kioskin yhteiset tuotekuvat',refresh:'Paivita',hero:'Tarkastele yhteisia tuotekuvia, kayttoa ja kayttamattomia tiedostoja.',all:'Kuvat',used:'Kaytossa',unused:'Ei kaytossa',search:'Haku',ph:'Hae nimella tai tiedostonimella',only:'Nayta vain kayttamattomat',loading:'Ladataan kuvia...',empty:'Suodatusta vastaavia kuvia ei loytynyt.',preview:'Esikatselu',file:'Tiedosto',type:'Tyyppi',size:'Koko',uploaded:'Ladattu',creator:'Luonut',usage:'Kaytto',close:'Sulje',del:'Poista kayttamaton kuva',delTitle:'Poistetaanko kuva?',delText:'Kuva poistetaan pysyvasti kirjastosta ja Blob Storagesta. Toimintoa ei voi perua.',cancel:'Peruuta',confirm:'Poista pysyvasti',deleting:'Poistetaan kuvaa...',deleted:'Kuva poistettiin',none:'Ei kaytossa millaan tuotteella',one:'Kaytossa 1 tuotteella',many:n=>`Kaytossa ${n} tuotteella`,unknown:'Tuntematon'}};const t=()=>tr[language]||tr.en;
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function api(url,opt={}){const r=await fetch(url,{headers:{Accept:'application/json'},...opt});const c=r.headers.get('content-type')||'';const b=c.includes('json')?await r.json().catch(()=>({})):await r.text();if(!r.ok)throw new Error(b?.details||b?.error||b||`HTTP ${r.status}`);return b;}
function text(){const x=t(),m={pageTitle:x.title,pageSubtitle:x.sub,refreshButton:x.refresh,heroTitle:x.title,heroText:x.hero,totalLabel:x.all,usedLabel:x.used,unusedLabel:x.unused,searchLabel:x.search,unusedOnlyLabel:x.only,previewTitle:x.preview,fileLabel:x.file,typeLabel:x.type,sizeLabel:x.size,uploadedLabel:x.uploaded,creatorLabel:x.creator,usageLabel:x.usage,previewClose:x.close,previewDelete:x.del,deleteTitle:x.delTitle,deleteText:x.delText,cancelDelete:x.cancel,confirmDelete:x.confirm};Object.entries(m).forEach(([id,v])=>document.getElementById(id).textContent=v);searchInput.placeholder=x.ph;render();if(selected&&previewDialog.open)fillPreview(selected);}
async function load(){status.textContent=t().loading;status.className='status show loading';refreshButton.disabled=true;try{images=await api(API);status.className='status';status.textContent='';summary();render();}catch(e){status.textContent=e.message;status.className='status show error';}finally{refreshButton.disabled=false;}}
function summary(){const used=images.filter(i=>+i.productUsageCount>0).length;totalCount.textContent=images.length;usedCount.textContent=used;unusedCount.textContent=images.length-used;}
function usage(n){return n===0?t().none:n===1?t().one:t().many(n)}
function render(){const q=searchInput.value.trim().toLowerCase(),list=images.filter(i=>(!unusedOnly.checked||+i.productUsageCount===0)&&(!q||[i.displayName,i.originalFileName,i.createdBy].filter(Boolean).join(' ').toLowerCase().includes(q)));imageGrid.innerHTML=list.length?list.map(card).join(''):`<div class="empty">${esc(t().empty)}</div>`;}
function card(i){const n=+i.productUsageCount||0;return `<article class="image-management-card ${n?'':'unused'}"><button class="image-card-preview" data-action="preview" data-id="${i.imageAssetId}"><img src="${esc(i.contentUrl)}" alt="" loading="lazy"></button><div class="image-card-content"><div class="image-card-title-row"><strong title="${esc(i.displayName)}">${esc(i.displayName||i.originalFileName)}</strong><span class="usage-pill ${n?'used':'unused'}">${n}</span></div><span class="image-file-name">${esc(i.originalFileName||'')}</span><small>${esc(usage(n))}</small></div><div class="image-card-actions"><button class="secondary" data-action="preview" data-id="${i.imageAssetId}">${esc(t().preview)}</button><button class="danger" data-action="delete" data-id="${i.imageAssetId}" ${n?'disabled':''}>${esc(t().del)}</button></div></article>`}
function openPreview(id){selected=images.find(i=>+i.imageAssetId===+id);if(!selected)return;fillPreview(selected);previewDialog.showModal();}
function fillPreview(i){const n=+i.productUsageCount||0;previewTitle.textContent=i.displayName||t().preview;previewSubtitle.textContent=`#${i.imageAssetId}`;previewImage.src=i.contentUrl;previewFile.textContent=i.originalFileName||'-';previewType.textContent=i.contentType||t().unknown;previewSize.textContent=bytes(i.fileSize);previewUploaded.textContent=date(i.createdAt);previewCreator.textContent=i.createdBy||t().unknown;previewUsage.textContent=usage(n);previewDelete.disabled=n>0;}
function askDelete(id){const i=images.find(x=>+x.imageAssetId===+id);if(!i||+i.productUsageCount>0)return;pendingDelete=i;deleteImage.src=i.contentUrl;deleteName.textContent=i.displayName||i.originalFileName;deleteFile.textContent=i.originalFileName||'';deleteStatus.className='status';deleteStatus.textContent='';if(previewDialog.open)previewDialog.close();deleteDialog.showModal();}
async function remove(){if(!pendingDelete)return;confirmDelete.disabled=true;deleteStatus.textContent=t().deleting;deleteStatus.className='status show loading';try{await api(`${API}/${pendingDelete.imageAssetId}`,{method:'DELETE'});images=images.filter(i=>+i.imageAssetId!==+pendingDelete.imageAssetId);deleteDialog.close();pendingDelete=null;summary();render();toast(t().deleted);}catch(e){deleteStatus.textContent=e.message;deleteStatus.className='status show error';}finally{confirmDelete.disabled=false;}}
function bytes(v){const n=+v;if(!Number.isFinite(n))return t().unknown;return n<1000?`${n} B`:n<1e6?`${(n/1000).toFixed(1)} kB`:`${(n/1e6).toFixed(1)} MB`;}
function date(v){if(!v)return t().unknown;const d=new Date(v);return new Intl.DateTimeFormat(language==='sv'?'sv-FI':language==='fi'?'fi-FI':'en-FI',{dateStyle:'medium',timeStyle:'short',hour12:false}).format(d);}
function toast(m){toastEl.textContent=m;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),3000);}
const toastEl=$('#toast');languageSelect.value=language;text();languageSelect.onchange=()=>{language=languageSelect.value;localStorage.setItem('lunch-poc-language-v5',language);text()};refreshButton.onclick=load;searchInput.oninput=render;unusedOnly.onchange=render;confirmDelete.onclick=remove;previewDelete.onclick=()=>selected&&askDelete(selected.imageAssetId);imageGrid.onclick=e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;b.dataset.action==='preview'?openPreview(b.dataset.id):askDelete(b.dataset.id)};document.onclick=e=>{const b=e.target.closest('[data-close]');if(b)document.getElementById(b.dataset.close).close()};load();