const API_BASE = 'https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api';
const USER_KEY = 'lunch-poc-current-user-v17';
const LANGUAGE_KEY = 'lunch-poc-language-v5';

let currentUser;
try { currentUser = JSON.parse(localStorage.getItem(USER_KEY)); } catch {}
if (!currentUser?.employeeNumber) location.replace('login.html');

const isGuest = document.body.dataset.orderType === 'guest';
let language = localStorage.getItem(LANGUAGE_KEY) || 'en';
let menuWeeksByMonday = new Map();
let menuCycleNames = new Set();
let menuData = [];
let salads = [];
let savedSaladOrders = {};
let workingSaladOrders = {};
let savedOrders = {};
let workingOrders = {};
let ready = false;
let dirty = false;
let saving = false;
let toastTimer;

const ui = {
    en: { title:'Order lunch', guestTitle:'Guest lunch', week:'Week', service:'Lunch service', order:'Order lunch', guest:'Order guest lunch', guestHelp:'Guests, subcontractors and interns', myOrders:'My orders', logout:'Log out', employee:'Employee', simulate:'POC: Simulate Friday', deadline:'Daily deadline 08:30', deadlineHelp:'Orders can be changed until the deadline.', today:'Today', menu:'Lunch menu', noMenu:'No dishes configured', none:'No lunches selected', selected:n=>`${n} lunch${n===1?'':'es'} selected`, saved:'Your orders are saved', nothing:'Nothing to save', unsaved:'Unsaved changes', save:'Save changes', saveShort:'Save', savedShort:'Saved', saving:'Saving...', savedToast:'Lunch orders saved', saveFailed:'Could not save lunch orders', loading:'Loading menu and orders...', loadFailed:'Could not load menu or orders', remove:'Remove one', add:'Add one', locked:'Ordering closed at 08:30', lockedHelp:'Today’s order is visible but can no longer be changed.', guestBanner:'Guest lunch order', guestAudience:'For guests, subcontractors and interns', workTask:'Work task / project', workPlaceholder:'Example: Project 1234, supplier visit', workRequired:'Required for guest lunch orders.', noGuest:'No guest lunches selected', guestSelected:n=>`${n} guest lunch${n===1?'':'es'} selected`, enterProject:'Enter work task / project', guestSaved:'Guest lunch order saved', saveGuest:'Save guest order', requiredToast:'Work task / project is required', backOwn:'Back to own lunch order', source:n=>`Menu loaded from Azure, ${n}-week rotation.`, salads:'Salads' },
    sv: { title:'Beställ lunch', guestTitle:'Gästlunch', week:'Vecka', service:'Lunchtjänst', order:'Beställ lunch', guest:'Beställ gästlunch', guestHelp:'Gäster, underleverantörer och praktikanter', myOrders:'Mina beställningar', logout:'Logga ut', employee:'Anställd', simulate:'POC: Simulera fredag', deadline:'Daglig deadline 08:30', deadlineHelp:'Beställningar kan ändras fram till deadline.', today:'I dag', menu:'Lunchmeny', noMenu:'Inga rätter konfigurerade', none:'Inga luncher valda', selected:n=>`${n} lunch${n===1?'':'er'} vald${n===1?'':'a'}`, saved:'Dina beställningar är sparade', nothing:'Inget att spara', unsaved:'Osparade ändringar', save:'Spara ändringar', saveShort:'Spara', savedShort:'Sparat', saving:'Sparar...', savedToast:'Lunchbeställningarna sparades', saveFailed:'Kunde inte spara lunchbeställningarna', loading:'Laddar meny och beställningar...', loadFailed:'Kunde inte ladda meny eller beställningar', remove:'Ta bort en', add:'Lägg till en', locked:'Beställningen stängde 08:30', lockedHelp:'Dagens beställning visas men kan inte längre ändras.', guestBanner:'Beställ gästlunch', guestAudience:'För gäster, underleverantörer och praktikanter', workTask:'Arbetsuppgift / projekt', workPlaceholder:'Exempel: Projekt 1234, leverantörsbesök', workRequired:'Obligatoriskt för gästlunchbeställningar.', noGuest:'Inga gästluncher valda', guestSelected:n=>`${n} gästlunch${n===1?'':'er'} vald${n===1?'':'a'}`, enterProject:'Ange arbetsuppgift / projekt', guestSaved:'Gästlunchbeställningen sparades', saveGuest:'Spara gästbeställning', requiredToast:'Arbetsuppgift / projekt krävs', backOwn:'Tillbaka till egen lunchbeställning', source:n=>`Menyn laddades från Azure, ${n}-veckors rotation.`, salads:'Sallader' },
    fi: { title:'Tilaa lounas', guestTitle:'Vieraslounas', week:'Viikko', service:'Lounaspalvelu', order:'Tilaa lounas', guest:'Tilaa vieraslounas', guestHelp:'Vieraat, alihankkijat ja harjoittelijat', myOrders:'Omat tilaukset', logout:'Kirjaudu ulos', employee:'Työntekijä', simulate:'POC: Simuloi perjantai', deadline:'Päivittäinen määräaika 08:30', deadlineHelp:'Tilauksia voi muuttaa määräaikaan asti.', today:'Tänään', menu:'Lounaslista', noMenu:'Ruokia ei ole määritetty', none:'Ei valittuja lounaita', selected:n=>`${n} lounas${n===1?'':'ta'} valittu`, saved:'Tilauksesi on tallennettu', nothing:'Ei tallennettavaa', unsaved:'Tallentamattomia muutoksia', save:'Tallenna muutokset', saveShort:'Tallenna', savedShort:'Tallennettu', saving:'Tallennetaan...', savedToast:'Lounastilaukset tallennettiin', saveFailed:'Lounastilausten tallennus epäonnistui', loading:'Ladataan ruokalistaa ja tilauksia...', loadFailed:'Ruokalistan tai tilausten lataaminen epäonnistui', remove:'Poista yksi', add:'Lisää yksi', locked:'Tilaus sulkeutui klo 08.30', lockedHelp:'Tämän päivän tilaus näkyy, mutta sitä ei voi enää muuttaa.', guestBanner:'Tilaa vieraslounas', guestAudience:'Vieraille, alihankkijoille ja harjoittelijoille', workTask:'Työtehtävä / projekti', workPlaceholder:'Esimerkki: Projekti 1234, toimittajavierailu', workRequired:'Pakollinen vieraslounastilauksille.', noGuest:'Ei valittuja vieraslounaita', guestSelected:n=>`${n} vieraslounas${n===1?'':'ta'} valittu`, enterProject:'Anna työtehtävä / projekti', guestSaved:'Vieraslounastilaus tallennettiin', saveGuest:'Tallenna vierastilaus', requiredToast:'Työtehtävä / projekti vaaditaan', backOwn:'Takaisin omaan lounastilaukseen', source:n=>`Ruokalista ladattiin Azuresta, ${n} viikon kierto.`, salads:'Salaatit' }
};

const names = {
    days: [
        {en:'Monday',sv:'Måndag',fi:'Maanantai'}, {en:'Tuesday',sv:'Tisdag',fi:'Tiistai'},
        {en:'Wednesday',sv:'Onsdag',fi:'Keskiviikko'}, {en:'Thursday',sv:'Torsdag',fi:'Torstai'},
        {en:'Friday',sv:'Fredag',fi:'Perjantai'}
    ],
    categories: {
        Main:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'}, Vegetarian:{en:'Vegetarian',sv:'Vegetarisk',fi:'Kasvisruoka'},
        Soup:{en:'Soup',sv:'Soppa',fi:'Keitto'}, Salad:{en:'Salad',sv:'Sallad',fi:'Salaatti'}, Dessert:{en:'Dessert',sv:'Dessert',fi:'Jälkiruoka'}
    }
};

const weekElement = document.querySelector('#week');
const saveButton = document.querySelector('#saveButton');
const headerSave = document.querySelector('#headerSave');
const summary = document.querySelector('#selectionSummary');
const changeSummary = document.querySelector('#changeSummary');
const workTask = document.querySelector('#workTask');
const menuSource = document.querySelector('#menuSource');

function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function mondayOf(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x;}
function effectiveToday(){const d=new Date();d.setHours(0,0,0,0);if(document.querySelector('#simulateFriday')?.checked)d.setDate(d.getDate()+((5-d.getDay()+7)%7));return d;}
function shownDates(){const today=effectiveToday(),wd=today.getDay();if(wd===0||wd===6){const monday=new Date(today);monday.setDate(today.getDate()+((8-wd)%7));return Array.from({length:5},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);return d;});}const dates=[];const friday=new Date(today);friday.setDate(today.getDate()+(5-wd));for(let d=new Date(today);d<=friday;d.setDate(d.getDate()+1))dates.push(new Date(d));if(wd===5){const monday=new Date(today);monday.setDate(today.getDate()+3);for(let i=0;i<5;i++){const d=new Date(monday);d.setDate(monday.getDate()+i);dates.push(d);}}return dates;}
function displayedRange(){const dates=shownDates();return{dateFrom:dateKey(dates[0]),dateTo:dateKey(dates[dates.length-1])};}
function deadlinePassed(){const n=new Date();return n.getHours()>8||(n.getHours()===8&&n.getMinutes()>=30);}
function dayLocked(id){return id===dateKey(effectiveToday())&&deadlinePassed();}
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const start=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-start)/86400000)+1)/7);}
function escapeHtml(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function orderKey(date,mealId){return `${date}:${mealId}`;}
function quantity(date,mealId){return Number(workingOrders[orderKey(date,mealId)]||0);}
function saladKey(date,id){return `${date}:${id}`;}
function saladQuantity(date,id){return Number(workingSaladOrders[saladKey(date,id)]||0);}
function total(){return Object.values(workingOrders).reduce((s,v)=>s+Number(v),0);}
function taskValid(){return !isGuest||Boolean(workTask.value.trim());}

async function apiFetch(path,options={}){const response=await fetch(`${API_BASE}${path}`,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const type=response.headers.get('content-type')||'';const payload=type.includes('application/json')?await response.json():await response.text();if(!response.ok)throw new Error(payload?.details||payload?.error||payload||`HTTP ${response.status}`);return payload;}

async function loadSalads(){salads=await apiFetch('/salads');}
async function loadMenusForShownDates(){const mondayKeys=[...new Set(shownDates().map(date=>dateKey(mondayOf(date))))];const results=await Promise.all(mondayKeys.map(async mondayKey=>[mondayKey,await apiFetch(`/menu/current?date=${encodeURIComponent(mondayKey)}`)]));menuWeeksByMonday=new Map(results);menuCycleNames=new Set(results.map(([,menu])=>menu.cycleName).filter(Boolean));}
function saladName(x){return language==='fi'?(x.nameFi||x.nameFI||x.nameSv||x.nameSV||x.nameEn||x.nameEN):language==='sv'?(x.nameSv||x.nameSV||x.nameEn||x.nameEN||x.nameFi||x.nameFI):(x.nameEn||x.nameEN||x.nameSv||x.nameSV||x.nameFi||x.nameFI);}
function mealName(m){return language==='fi'?(m.nameFI||m.nameSV||m.nameEN):language==='sv'?(m.nameSV||m.nameEN||m.nameFI):(m.nameEN||m.nameSV||m.nameFI);}
function buildMenu(){const today=effectiveToday();return shownDates().map(date=>{const dayNo=((date.getDay()+6)%7)+1;const apiWeek=menuWeeksByMonday.get(dateKey(mondayOf(date)));const apiDay=apiWeek?.days?.find(d=>d.dayNumber===dayNo);return{id:dateKey(date),day:names.days[dayNo-1][language],date:`${String(date.getDate()).padStart(2,'0')}.${String(date.getMonth()+1).padStart(2,'0')}`,note:dateKey(date)===dateKey(today)?ui[language].today:'',meals:(apiDay?.meals||[]).map(m=>({mealId:Number(m.mealId),name:mealName(m),category:names.categories[m.category]?.[language]||m.category||''})).filter(m=>m.name&&Number.isInteger(m.mealId))};});}

function fromApi(payload){const result={};for(const o of payload.orders||[])result[orderKey(o.menuDate,Number(o.mealId))]=Number(o.quantity)||0;return result;}
function orderLines(){const allowed=new Set(menuData.flatMap(day=>day.meals.map(meal=>orderKey(day.id,meal.mealId))));return Object.entries(workingOrders).filter(([k,v])=>allowed.has(k)&&Number(v)>0).map(([k,v])=>{const i=k.lastIndexOf(':');return{menuDate:k.slice(0,i),mealId:Number(k.slice(i+1)),quantity:Number(v),...(isGuest?{workTask:workTask.value.trim()}:{})};});}
function saladLines(){return Object.entries(workingSaladOrders).filter(([,v])=>Number(v)>0).map(([k,v])=>{const i=k.lastIndexOf(':');return{menuDate:k.slice(0,i),saladId:Number(k.slice(i+1)),quantity:Number(v)};});}
async function loadSaladOrders(){const route=isGuest?'/guest-salad-orders':'/salad-orders';const person=isGuest?'hostEmployeeNo':'employeeNo';const payload=await apiFetch(`${route}?${person}=${currentUser.employeeNo}&dateFrom=${shownDates[0]}&dateTo=${shownDates.at(-1)}`);const result={};for(const x of payload.saladOrders||[])result[saladKey(x.menuDate,x.saladId)]=Number(x.quantity)||0;savedSaladOrders=result;workingSaladOrders=structuredClone(result);}
async function saveSaladOrders(){const route=isGuest?'/guest-salad-orders':'/salad-orders';const body={dateFrom:shownDates[0],dateTo:shownDates.at(-1),saladOrders:saladLines(),...(isGuest?{hostEmployeeNo:currentUser.employeeNo,workTask:workTask.value.trim()}:{employeeNo:currentUser.employeeNo})};await apiFetch(route,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});savedSaladOrders=structuredClone(workingSaladOrders);}
async function loadOrders(){const range=displayedRange();const query=new URLSearchParams(isGuest?{hostEmployeeNo:String(currentUser.employeeNumber),dateFrom:range.dateFrom,dateTo:range.dateTo}:{employeeNo:String(currentUser.employeeNumber),dateFrom:range.dateFrom,dateTo:range.dateTo});const payload=await apiFetch(`/${isGuest?'guest-orders':'orders'}?${query}`);savedOrders=fromApi(payload);workingOrders=structuredClone(savedOrders);if(isGuest&&payload.orders?.length)workTask.value=payload.orders[0].workTask||'';}

function updateSummary(){const t=ui[language],n=total();summary.textContent=isGuest?(n?t.guestSelected(n):t.noGuest):(n?t.selected(n):t.none);if(!ready)changeSummary.textContent=t.loading;else if(saving)changeSummary.textContent=t.saving;else if(isGuest&&n&&!taskValid())changeSummary.textContent=t.enterProject;else if(dirty)changeSummary.textContent=t.unsaved;else changeSummary.textContent=n?t.saved:t.nothing;const can=ready&&dirty&&!saving&&taskValid();saveButton.disabled=!can;headerSave.disabled=!can;headerSave.textContent=saving?t.saving:(dirty?t.saveShort:t.savedShort);}
function render(){const t=ui[language];if(!ready){weekElement.innerHTML=`<div class="empty-state"><strong>${escapeHtml(t.loading)}</strong></div>`;updateSummary();return;}weekElement.innerHTML=menuData.map((day,index)=>{const count=day.meals.reduce((s,m)=>s+quantity(day.id,m.mealId),0)+salads.reduce((s,x)=>s+saladQuantity(day.id,x.saladId),0),open=index===0||count>0,locked=dayLocked(day.id);return`<article class="day ${open?'open':''} ${locked?'deadline-locked':''}" data-day="${day.id}"><button class="day-toggle" type="button" aria-expanded="${open}"><span class="chevron"></span><span class="day-name"><strong>${escapeHtml(day.day)} ${day.date}</strong><span>${escapeHtml(locked?t.locked:(day.note||t.menu))}</span></span><span class="day-total ${count?'has-orders':''}">🍴 ${count}</span></button><div class="day-content">${locked?`<div class="deadline-lock-note">${escapeHtml(t.lockedHelp)}</div>`:''}${day.meals.length?day.meals.map(m=>`<div class="meal-row"><div class="meal-name"><strong>${escapeHtml(m.name)}</strong><span>${escapeHtml(m.category)}</span></div><div class="stepper" data-meal-id="${m.mealId}"><button class="minus" type="button" ${locked||quantity(day.id,m.mealId)===0?'disabled':''}>−</button><output>${quantity(day.id,m.mealId)}</output><button class="plus" type="button" ${locked?'disabled':''}>+</button></div></div>`).join(''):`<div class="empty-state"><strong>${escapeHtml(t.noMenu)}</strong></div>`}<div class="salad-section"><h3>${escapeHtml(t.salads)}</h3>${salads.map(x=>`<div class="meal-row salad-row"><div class="meal-name"><strong>${escapeHtml(saladName(x))}</strong></div><div class="stepper" data-salad-id="${x.saladId}"><button class="minus" type="button" ${locked||saladQuantity(day.id,x.saladId)===0?'disabled':''}>−</button><output>${saladQuantity(day.id,x.saladId)}</output><button class="plus" type="button" ${locked?'disabled':''}>+</button></div></div>`).join('')}</div></div></article>`;}).join('');updateSummary();}
function markDirty(){dirty=JSON.stringify(workingOrders)!==JSON.stringify(savedOrders)||JSON.stringify(workingSaladOrders)!==JSON.stringify(savedSaladOrders);updateSummary();}

weekElement.addEventListener('click',e=>{const toggle=e.target.closest('.day-toggle');if(toggle){const day=toggle.closest('.day');day.classList.toggle('open');toggle.setAttribute('aria-expanded',String(day.classList.contains('open')));return;}const stepper=e.target.closest('.stepper'),button=e.target.closest('.stepper button');if(!stepper||!button||saving)return;const date=button.closest('.day').dataset.day;if(dayLocked(date)){showToast(ui[language].locked);return;}const isSalad=stepper.dataset.saladId!==undefined,id=Number(isSalad?stepper.dataset.saladId:stepper.dataset.mealId),key=isSalad?saladKey(date,id):orderKey(date,id),old=isSalad?saladQuantity(date,id):quantity(date,id),next=button.classList.contains('plus')?old+1:Math.max(0,old-1);const target=isSalad?workingSaladOrders:workingOrders;if(next)target[key]=next;else delete target[key];markDirty();render();});

async function saveOrders(){if(!dirty||saving)return;if(isGuest&&!taskValid()){document.querySelector('#taskPanel').classList.add('invalid');workTask.focus();showToast(ui[language].requiredToast);return;}saving=true;updateSummary();try{const range=displayedRange();await apiFetch(`/${isGuest?'guest-orders':'orders'}`,{method:'PUT',body:JSON.stringify(isGuest?{hostEmployeeNo:Number(currentUser.employeeNumber),...range,orders:orderLines()}:{employeeNo:Number(currentUser.employeeNumber),...range,orders:orderLines()})});savedOrders=structuredClone(workingOrders);dirty=false;showToast(isGuest?ui[language].guestSaved:ui[language].savedToast);}catch(e){console.error(e);showToast(`${ui[language].saveFailed}: ${e.message}`);}finally{saving=false;updateSummary();}}
saveButton.addEventListener('click',saveOrders);headerSave.addEventListener('click',saveOrders);if(isGuest)workTask.addEventListener('input',()=>{if(workTask.value.trim())document.querySelector('#taskPanel').classList.remove('invalid');updateSummary();});

function applyText(){const t=ui[language];document.documentElement.lang=language;document.title=isGuest?t.guestTitle:t.title;document.querySelector('.header-title h1').textContent=isGuest?t.guestTitle:t.title;document.querySelector('.header-title span').textContent=`${t.week} ${isoWeek(effectiveToday())}`;document.querySelector('.notice strong').textContent=t.deadline;document.querySelector('.notice span').textContent=t.deadlineHelp;document.querySelector('#simulateFridayLabel').textContent=t.simulate;saveButton.textContent=isGuest?t.saveGuest:t.save;if(menuSource&&menuCycleNames.size)menuSource.textContent=[...menuCycleNames].join(' / ');if(isGuest){document.querySelector('.back-button').setAttribute('aria-label',t.backOwn);document.querySelector('.guest-banner strong').textContent=t.guestBanner;document.querySelector('.guest-banner span').textContent=t.guestAudience;document.querySelector('label[for="workTask"]').childNodes[0].textContent=`${t.workTask} `;workTask.placeholder=t.workPlaceholder;document.querySelector('#taskHelp').textContent=t.workRequired;}else{const nav=document.querySelectorAll('.drawer .nav-item');document.querySelector('.drawer-head strong').textContent=t.service;nav[0].textContent=t.order;nav[1].innerHTML=`<span>${t.guest}</span><small>${t.guestHelp}</small>`;nav[2].textContent=t.myOrders;nav[3].textContent=t.logout;document.querySelector('#currentUserNumber').textContent=`${t.employee} ${currentUser.employeeNumber}`;}}

const drawer=document.querySelector('#drawer');if(drawer){const scrim=document.querySelector('#scrim'),menuButton=document.querySelector('#menuButton');const setDrawer=open=>{drawer.classList.toggle('open',open);scrim.classList.toggle('visible',open);drawer.setAttribute('aria-hidden',String(!open));menuButton.setAttribute('aria-expanded',String(open));};menuButton.addEventListener('click',()=>setDrawer(true));document.querySelector('#closeMenu').addEventListener('click',()=>setDrawer(false));scrim.addEventListener('click',()=>setDrawer(false));}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3000);}
function initials(name){return String(name||'').split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase();}
document.querySelector('#currentUserName').textContent=currentUser.employeeName;if(document.querySelector('#userAvatar'))document.querySelector('#userAvatar').textContent=initials(currentUser.employeeName);document.querySelector('#logoutButton')?.addEventListener('click',()=>{localStorage.removeItem(USER_KEY);location.replace('login.html');});
const languageSelect=document.querySelector('#languageSelect');languageSelect.value=language;languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);if(ready)menuData=buildMenu();applyText();render();});
const simulateFriday=document.querySelector('#simulateFriday');simulateFriday.addEventListener('change',reload);
window.addEventListener('beforeunload',e=>{if(!dirty)return;e.preventDefault();e.returnValue='';});

async function reload(){ready=false;applyText();render();try{await Promise.all([loadMenusForShownDates(),loadSalads()]);menuData=buildMenu();await loadOrders();ready=true;dirty=false;applyText();render();}catch(e){console.error(e);weekElement.innerHTML=`<div class="empty-state"><strong>${escapeHtml(ui[language].loadFailed)}</strong><span>${escapeHtml(e.message)}</span></div>`;if(menuSource)menuSource.textContent=`API error: ${e.message}`;showToast(ui[language].loadFailed);}}
reload();
