const API_BASE = 'https://lunchapp-api-dev-bxf8hff5hmb7g5dv.swedencentral-01.azurewebsites.net/api';
const USER_KEY = 'lunch-poc-current-user-v17';
const LANGUAGE_KEY = 'lunch-poc-language-v5';
let currentUser;
try { currentUser = JSON.parse(localStorage.getItem(USER_KEY)); } catch {}
const ownerType=currentUser?.ownerType==='external'?'external':'employee';const employeeNumber=Number(currentUser?.employeeNumber||currentUser?.employeeNo),externalAccountId=Number(currentUser?.externalAccountId);if(ownerType==='external'?!externalAccountId:!employeeNumber)location.replace('login.html');
let language = localStorage.getItem(LANGUAGE_KEY) || 'en';
let personalWeekOrders=[],personalMonthOrders=[],guestWeekOrders=[],guestMonthOrders=[];
let personalWeekSalads=[],personalMonthSalads=[],guestWeekSalads=[],guestMonthSalads=[];
let loadError=null;
const copy={
 en:{title:'My orders',week:'This week',overview:'Lunch overview',intro:'Check your personal and guest lunch orders for each weekday.',summary:'Summary',personalWeek:'Personal portions this week',guestWeek:'Guest portions this week',month:'Total portions this month',personal:'Personal',guest:'Guest',meals:'Main dishes',salads:'Salads',none:'No order',project:'Work task / project',menu:'Lunch menu',source:'Personal and guest meal and salad orders are loaded from Azure.',back:'Back to lunch ordering',loading:'Loading orders...',failed:'Could not load orders'},
 sv:{title:'Mina beställningar',week:'Den här veckan',overview:'Lunchöversikt',intro:'Kontrollera dina egna lunchbeställningar och gästluncher för varje vardag.',summary:'Sammanfattning',personalWeek:'Egna portioner den här veckan',guestWeek:'Gästportioner den här veckan',month:'Totalt antal portioner den här månaden',personal:'Egna beställningar',guest:'Gästbeställningar',meals:'Huvudrätter',salads:'Sallader',none:'Ingen beställning',project:'Arbetsuppgift / projekt',menu:'Lunchmeny',source:'Egna och gästers mat- och salladsbeställningar hämtas från Azure.',back:'Tillbaka till lunchbeställning',loading:'Laddar beställningar...',failed:'Kunde inte ladda beställningarna'},
 fi:{title:'Omat tilaukset',week:'Tämä viikko',overview:'Lounasyhteenveto',intro:'Tarkista omat lounastilauksesi ja vieraslounaat jokaiselle arkipäivälle.',summary:'Yhteenveto',personalWeek:'Omat annokset tällä viikolla',guestWeek:'Vierasannokset tällä viikolla',month:'Annoksia yhteensä tässä kuussa',personal:'Omat tilaukset',guest:'Vieraiden tilaukset',meals:'Pääruoat',salads:'Salaatit',none:'Ei tilausta',project:'Työtehtävä / projekti',menu:'Lounaslista',source:'Omat ja vieraiden ruoka- ja salaattitilaukset ladataan Azuresta.',back:'Takaisin lounastilaukseen',loading:'Ladataan tilauksia...',failed:'Tilausten lataaminen epäonnistui'}
};
const weekdays=[{en:'Monday',sv:'Måndag',fi:'Maanantai'},{en:'Tuesday',sv:'Tisdag',fi:'Tiistai'},{en:'Wednesday',sv:'Onsdag',fi:'Keskiviikko'},{en:'Thursday',sv:'Torsdag',fi:'Torstai'},{en:'Friday',sv:'Fredag',fi:'Perjantai'}];
const categoryNames={Main:{en:'Main dish',sv:'Huvudrätt',fi:'Pääruoka'},Vegetarian:{en:'Vegetarian',sv:'Vegetarisk',fi:'Kasvisruoka'},Soup:{en:'Soup',sv:'Soppa',fi:'Keitto'},Dessert:{en:'Dessert',sv:'Dessert',fi:'Jälkiruoka'}};
const $=s=>document.querySelector(s),ordersList=$('#ordersList'),languageSelect=$('#languageSelect');
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function mondayOf(d){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x;}
function weekDates(){const m=mondayOf(new Date());return Array.from({length:5},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d;});}
function monthRange(){const n=new Date();return{dateFrom:dateKey(new Date(n.getFullYear(),n.getMonth(),1)),dateTo:dateKey(new Date(n.getFullYear(),n.getMonth()+1,0))};}
function formatDate(d){return `${String(d.getDate()).padStart(2,'0')}.${String(d.getMonth()+1).padStart(2,'0')}`;}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function mealName(o){return language==='sv'?(o.nameSV||o.nameEN||o.nameFI):language==='fi'?(o.nameFI||o.nameSV||o.nameEN):(o.nameEN||o.nameSV||o.nameFI);}
function saladName(o){return language==='sv'?(o.nameSv||o.nameSV||o.nameEn||o.nameEN||o.nameFi||o.nameFI):language==='fi'?(o.nameFi||o.nameFI||o.nameSv||o.nameSV||o.nameEn||o.nameEN):(o.nameEn||o.nameEN||o.nameSv||o.nameSV||o.nameFi||o.nameFI);}
function category(v){return categoryNames[v]?.[language]||v||'';}
async function api(path){const r=await fetch(`${API_BASE}${path}`,{headers:{Accept:'application/json'}}),p=await r.json().catch(()=>null);if(!r.ok)throw new Error(p?.details||p?.error||`HTTP ${r.status}`);return p;}
function query(person,dateFrom,dateTo){return new URLSearchParams(ownerType==='external'?{externalAccountId:String(externalAccountId),dateFrom,dateTo}:{[person]:String(employeeNumber),dateFrom,dateTo});}
async function loadSet(dateFrom,dateTo){const pq=query('employeeNo',dateFrom,dateTo);if(ownerType==='external'){const [pm,ps]=await Promise.all([api(`/orders?${pq}`),api(`/salad-orders?${pq}`)]);return[pm.orders||[],ps.saladOrders||[],[],[]];}const gq=query('hostEmployeeNo',dateFrom,dateTo);const [pm,ps,gm,gs]=await Promise.all([api(`/orders?${pq}`),api(`/salad-orders?${pq}`),api(`/guest-orders?${gq}`),api(`/guest-salad-orders?${gq}`)]);return[pm.orders||[],ps.saladOrders||[],gm.orders||[],gs.saladOrders||[]];}
function rows(items,type,isGuest){if(!items.length)return'';return `<div class="my-order-subgroup"><h4>${esc(type==='salad'?copy[language].salads:copy[language].meals)}</h4>${items.map(o=>`<div class="my-order-line"><div><strong>${esc(type==='salad'?saladName(o):mealName(o))}</strong><span>${type==='salad'?esc(copy[language].salads):esc(category(o.category))}${isGuest&&o.workTask?` · ${esc(copy[language].project)}: ${esc(o.workTask)}`:''}</span></div><b>× ${Number(o.quantity)||0}</b></div>`).join('')}</div>`;}
function group(label,meals,salads,isGuest){if(!meals.length&&!salads.length)return'';return `<div class="my-order-group ${isGuest?'guest':''}"><h3>${esc(label)}</h3>${rows(meals,'meal',isGuest)}${rows(salads,'salad',isGuest)}</div>`;}
function apply(){const t=copy[language];document.documentElement.lang=language;document.title=t.title;$('#pageTitle').textContent=t.title;$('#pageSubtitle').textContent=t.week;$('#introEyebrow').textContent=t.overview;$('#weekHeading').textContent=t.week;$('#introText').textContent=t.intro;$('#summaryHeading').textContent=t.summary;$('#personalLabel').textContent=t.personalWeek;$('#guestLabel').textContent=t.guestWeek;$('#monthLabel').textContent=t.month;$('#sourceNote').textContent=loadError?`${t.failed}: ${loadError.message}`:t.source;$('#backButton').setAttribute('aria-label',t.back);}
function total(a){return a.reduce((n,x)=>n+Number(x.quantity||0),0);}
function render(){apply();if(loadError){ordersList.innerHTML=`<div class="empty-state"><strong>${esc(copy[language].failed)}</strong><span>${esc(loadError.message)}</span></div>`;return;}ordersList.innerHTML=weekDates().map((d,i)=>{const k=dateKey(d),pm=personalWeekOrders.filter(x=>x.menuDate===k),ps=personalWeekSalads.filter(x=>x.menuDate===k),gm=guestWeekOrders.filter(x=>x.menuDate===k),gs=guestWeekSalads.filter(x=>x.menuDate===k),n=total([...pm,...ps,...gm,...gs]);return `<article class="my-order-day"><div class="my-order-day-head"><div><strong>${esc(weekdays[i][language])} ${formatDate(d)}</strong><span>${esc(n?copy[language].menu:copy[language].none)}</span></div><span class="day-total ${n?'has-orders':''}">🍴 ${n}</span></div>${n?`<div class="my-order-details">${group(copy[language].personal,pm,ps,false)}${group(copy[language].guest,gm,gs,true)}</div>`:`<div class="my-order-empty">${esc(copy[language].none)}</div>`}</article>`;}).join('');$('#personalTotal').textContent=String(total([...personalWeekOrders,...personalWeekSalads]));$('#guestTotal').textContent=String(total([...guestWeekOrders,...guestWeekSalads]));$('#monthTotal').textContent=String(total([...personalMonthOrders,...personalMonthSalads,...guestMonthOrders,...guestMonthSalads]));}
async function initialise(){apply();ordersList.innerHTML=`<div class="empty-state"><strong>${esc(copy[language].loading)}</strong></div>`;const d=weekDates(),month=monthRange();try{const [week,mon]=await Promise.all([loadSet(dateKey(d[0]),dateKey(d[4])),loadSet(month.dateFrom,month.dateTo)]);[personalWeekOrders,personalWeekSalads,guestWeekOrders,guestWeekSalads]=week;[personalMonthOrders,personalMonthSalads,guestMonthOrders,guestMonthSalads]=mon;loadError=null;}catch(e){console.error(e);loadError=e;}render();}
$('#currentUserName').textContent=currentUser.employeeName||currentUser.displayName||currentUser.cardHolderName||'Lunch user';if(ownerType==='external'){$('#guestLabel').closest('article').hidden=true;}$('#logoutButton').addEventListener('click',()=>{localStorage.removeItem(USER_KEY);location.replace('login.html');});languageSelect.value=language;languageSelect.addEventListener('change',()=>{language=languageSelect.value;localStorage.setItem(LANGUAGE_KEY,language);render();});initialise();
